### ISSUE TITLE
Central force problem

### ISSUE THREAD

**Issue by emptymalei** [kausalflow/hamilflow#13]
## Definition

A generic central force problem. 

- Lagrangian
- Equation of motion

## References

1. https://www.damtp.cam.ac.uk/user/tong/relativity/four.pdf

**Comment by cmp0xff** [comment]
Landau vol 1, sec. 14

If we reduce to 2d, $$L = \frac{m}{2} \left(\dot{r}^2 + r^2 \dot\phi^2\right) - V(r)\\,.$$

$L$ does not contain $\phi$ explicitly, making $\phi$ a cyclic variable. We have an integral of motion $l \equiv m r^2 \phi$.

$L$ does not contain $t$ explicitly. We have a second integral of motion, the energy
$$E = \frac{m}{2}\left(\dot r^2 + r^2 \dot\phi^2\right) + V(r) = \frac{m}{2} \dot{r}^2 + \frac{l}{2mr^2} + V(r)\\,.$$
We can derive
$$\frac{\mathbb{d}t}{\mathbb{d}r} = \left(\frac{2}{m}\left(E-V(r)\right) - \frac{l^2}{m^2 r^2}\right)^{-1/2}\\,.$$

**Comment by emptymalei** [comment]
For future reference:

https://www.aanda.org/articles/aa/full_html/2018/11/aa33162-18/aa33162-18.html

**Comment by emptymalei** [comment]
After some explorations in #50 , I have a feeling that a generic numerical integral of arbitrary initial condition and parameters are time consuming for our purpose. 
I propose we reduce this into different scenarios and provide more dedicated formulations.
- [ ] Circular/elliptical orbits
- [ ] Parabolic orbits

Free fall is not interesting for our use case.
