### ISSUE TITLE
Separate simple harmonic oscillator from the damped oscillators

### ISSUE THREAD

**Issue by cmp0xff** [kausalflow/hamilflow#34]
A simple harmonic oscillator, without damping, can be described by the Lagrangian action
$$S_L[x] = \int_{t_0}^{t_1} \mathbb{d}t \left\\{\frac{1}{2} m \dot x^2 - \frac{1}{2} m \omega x^2 \right\\}\\,.$$
This action is so important that I think it makes sense to single out the simple harmonic oscillator.

I also propose to have damped oscillators as a generalisation (mathematical-physically), or a subclass, of simple harmonic oscillators.

**Comment by cmp0xff** [comment]
This separation also enables #10. With damping, I don't know how to start a Hamiltonian description..

**Comment by emptymalei** [comment]
Makes sense. I can work on this.
