### ISSUE TITLE
How can we see results of deploy-preview?

### ISSUE THREAD

**Issue by cmp0xff** [kausalflow/hamilflow#74]
We probably need some instructions. I cannot easily find it.

**Comment by emptymalei** [comment]
Once the Actions is done, a bot will post a comment in the PR
![Screenshot 2024-08-05 at 19 13 09](https://github.com/user-attachments/assets/18886748-3190-4b94-ab00-d9a30894a5e5)

When a PR is merged, the preview is removed.
![Screenshot 2024-08-05 at 19 13 24](https://github.com/user-attachments/assets/650f4b81-e724-4e7d-9713-e65c5e89f367)


This is how it works.


![Screenshot 2024-08-05 at 19 14 33](https://github.com/user-attachments/assets/517ea6ad-6105-49c5-bf36-bef46a821cf6)

**Comment by cmp0xff** [comment]
Thanks! Understood.
